name: jimmys
description: Manage scheduling of workouts.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.5.0
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  firebase_core: ^2.17.0
  firebase_analytics: ^10.5.1
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2
  cloud_firestore: ^4.9.3

  english_words: ^4.0.0
  transparent_image: ^2.0.1
  flutter_spinkit: ^5.2.0
  provider: ^6.0.5
  azlistview: ^2.0.0
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  keyboard_dismisser: ^3.0.0
  sticky_headers: ^0.3.0+2
  glassy: ^0.0.6
  uuid: ^4.1.0
  collection: ^1.17.2
  measured_size: ^1.0.0
  gap: ^3.0.1
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/