// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6FBtx7EVF0dwstS3VJENUxIH6IvEpBic',
    appId: '1:385539961382:android:823c1af42b24b70a03ace7',
    messagingSenderId: '385539961382',
    projectId: 'jimmys-4d596d',
    storageBucket: 'jimmys-4d596d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWaH3HY6lONeOvkqCh-vwhGQhhKz_AblY',
    appId: '1:385539961382:ios:763bf2ea48ff09ab03ace7',
    messagingSenderId: '385539961382',
    projectId: 'jimmys-4d596d',
    storageBucket: 'jimmys-4d596d.appspot.com',
    androidClientId: '385539961382-8qngn1eu5jvsm4k23edtpn416c38d2l1.apps.googleusercontent.com',
    iosClientId: '385539961382-o6sl7vavt0mp31dq031f3ctv507e62ko.apps.googleusercontent.com',
    iosBundleId: 'com.mcalpinekeith.jimmys',
  );
}
